### ISSUE TITLE
T-Deck PLUS key backlight

### ISSUE THREAD

**Issue by VolosR** [Xinyuan-LilyGO/T-Deck#49]
Hello Lewis! 

I recently got T-Deck plus, and i noticed that when its booting keys are backlighted for a second.I cant find information how to
turn keys backlight in runtime. Is there any pin thet control keys light or is controled by keyboard firmwhare itself.

Thank you for your help!

Volos

**Comment by lewisxhe** [comment]
It will light up for a moment when it starts up. This is unavoidable. It is caused by the hardware selecting IO. The initial level at power-on causes the backlight to light up.

There is no backlight control during operation. You can change the source code to add functions. Keyboard source code path https://github.com/Xinyuan-LilyGO/T-Deck/blob/master/examples/Keyboard_ESP32C3/Keyboard_ESP32C3.ino
